### PR TITLE
fix(subscriptions): emit converter switch arms most-specific-first

### LINKED ISSUE #589: ConsumeContextConverterGenerator emits unreachable switch arms for inherited [EventType] records (CS8510) since 0.16.4
**Describe the bug**
Since 0.16.4 (PR #542), `ConsumeContextConverterGenerator` discovers all `[EventType]` types and emits one type-pattern switch arm per type in `MessageConsumeContext_Converters.g.cs`. The arms are emitted in discovery order with no inheritance-aware sorting, so when one `[EventType]` record inherits from another, the base-type arm can precede the derived-type arm. The derived arm is then subsumed and the build fails with `error CS8510: The pattern is unreachable`. The same code builds fine on 0.16.3.

In [`ConsumeContextConverterGenerator.cs`](https://github.com/Eventuous/eventuous/blob/0.16.4/src/Core/gen/Eventuous.Subscriptions.Generators/ConsumeContextConverterGenerator.cs):
- [`Generate`, L214](https://github.com/Eventuous/eventuous/blob/0.16.4/src/Core/gen/Eventuous.Subscriptions.Generators/ConsumeContextConverterGenerator.cs#L214) only applies `Distinct()` — no ordering — and [L241–L243](https://github.com/Eventuous/eventuous/blob/0.16.4/src/Core/gen/Eventuous.Subscriptions.Generators/ConsumeContextConverterGenerator.cs#L241-L243) emit the arms in that order.
- The order comes from [`DiscoverEventTypes`' namespace traversal, L257–L287](https://github.com/Eventuous/eventuous/blob/0.16.4/src/Core/gen/Eventuous.Subscriptions.Generators/ConsumeContextConverterGenerator.cs#L257-L287), which visits namespaces/types in declaration order — so a base type in namespace `Foo` is emitted before a derived type in `Foo.Bar`.

**To Reproduce**
1. Declare two event types where one inherits the other:
   ```csharp
   [EventType("V1.Base")]
   public record BaseEvent;

   [EventType("V1.Derived")]
   public sealed record DerivedEvent : BaseEvent;
   ```
2. Reference them from any project that uses Eventuous subscriptions (so the generator runs).
3. `dotnet build`
4. See `error CS8510: The pattern is unreachable. It has already been handled by a previous arm of the switch expression` in `MessageConsumeContext_Converters.g.cs`:
   ```csharp
   => context.Message switch {
       global::My.BaseEvent => new MessageConsumeContext<global::My.BaseEvent>(context),
       global::My.DerivedEvent => new MessageConsumeContext<global::My.DerivedEvent>(context), // CS8510
       _ => null
   };
   ```

**Expected behavior**
The generated switch compiles, and each message is matched to its most specific event type. Note the ordering is also a correctness issue: even where base-before-derived happens to compile, a derived event matches the base arm and gets wrapped as `MessageConsumeContext<BaseEvent>` instead of its concrete type.

A fix could sort arms most-derived-first before emitting — e.g. carry inheritance depth alongside the name from the `GetTypeSyntax` (L138) call sites and order by depth descending (then by name for deterministic incremental output) in `Generate` (L214):
```csharp
static int Depth(ITypeSymbol t) { var d = 0; for (var b = t.BaseType; b != null; b = b.BaseType) d++; return d; }
```
Any derived type is strictly deeper than its base, so no arm can subsume a later one — fixing both the CS8510 and the mismatched context type.

**Screenshots**
N/A — build output quoted above.

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 44)
 - .NET SDK: 10.0
 - Eventuous version: 0.16.4 (regression from 0.16.3)

**Additional context**
Introduced by the new `DiscoverEventTypes` step added in PR #542 (fix for #538), which scans the compilation and referenced assemblies for `[EventType]` types.

### PR DESCRIPTION
**Pull request by alexeyzimarev**
Fixes #589

## Problem

Since 0.16.4 (#542), `ConsumeContextConverterGenerator` discovers all `[EventType]` types and emits one type-pattern switch arm per type, in discovery order. When one message type is a supertype of another, its arm can come first and subsume the more specific arm, so the consuming project fails to build with `CS8510: The pattern is unreachable`. Namespace traversal goes outer to inner, so a base record in `Foo` always lands before a derived record in `Foo.Bar`.

It is not limited to `[EventType]` discovery: any scanned usage that brings in both a base and a derived type (for example `On<Base>` next to `On<Derived>`) takes the same path.

It is also a correctness problem. The reflection fallback in `MessageConsumeContextConverter` converts using the message's exact runtime type, so the generated converter only agrees with it when the most specific arm wins.

## Fix

Each candidate now carries a specificity rank: the number of its base classes plus all of its interfaces. A subtype always has strictly more supertypes than any of its supertypes, so emitting arms by rank descending keeps the arm of a type ahead of the arms of its supertypes.

Types of equal rank keep their discovery order (the sort is stable), which is still deterministic. This matters for types related only through generic variance, such as `IEnvelope<Zebra>` and `IEnvelope<Animal>` with `IEnvelope<out T>`: they have the same rank, so the rank cannot order them. Keeping discovery order means anything that compiled before this change still compiles. Variance-related message types declared broader-first still fail with CS8510, as they did before; ordering those correctly needs implicit-conversion checks across all candidate pairs on every generator run, which is not worth it until someone actually hits it.

The issue suggested sorting by base-class depth. That covers classes but not interfaces: every interface has depth zero, so `IAnyEvent` could still precede `IBookingEvent : IAnyEvent` and hit the same error. Counting interfaces as well covers both.

## Tests

The generator had no tests. `ConsumeContextConverterGeneratorTests` in `Eventuous.Tests.Subscriptions` runs the generator through `CSharpGeneratorDriver` and asserts that the output compiles without errors and that arms are ordered most-specific-first, for:

- the class inheritance case from the issue
- an interface chain with an implementing record, named so that alphabetical order is the opposite of the required order
- two covariantly related interfaces of equal rank, declared specific-first and named so that alphabetical order would put the broader one first

All three failed with CS8510 before the corresponding fix. The test project now references the generator project and the CodeAnalysis packages.

Verified locally on net10.0 only (137 tests in the project pass); net8.0 and net9.0 runtimes are not installed on my machine, so those rely on CI.

## Notes

No public API change, so no docs or plugin updates are needed.

Not addressed here: `GetTypeSyntax` prefixes keyword types with `global::`, so `IMessageConsumeContext<string>` generates `global::string` (CS1041). It predates this change and deserves its own issue.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: src/Core/gen/Eventuous.Subscriptions.Generators/ConsumeContextConverterGenerator.cs [hunk 1]
```diff
@@ -135,6 +135,19 @@ static bool IsPotentialUsage(SyntaxNode node, CancellationToken _) {
...
 
+    static (string Name, int Specificity)? GetCandidate(ITypeSymbol symbol)
+        => GetTypeSyntax(symbol) is { } name ? (name, GetSpecificity(symbol)) : null;
+
+    // A type always has strictly more supertypes (base classes and interfaces) than any of its supertypes has,
+    // so emitting switch arms by this count in descending order guarantees that no arm is subsumed by an earlier one
+    static int GetSpecificity(ITypeSymbol symbol) {
+        var count = symbol.AllInterfaces.Length;
+
+        for (var baseType = symbol.BaseType; baseType != null; baseType = baseType.BaseType) count++;
```
[the remark this answers is not in the document]
Comment (alexeyzimarev) [reply src/Core/gen/Eventuous.Subscriptions.Generators/ConsumeContextConverterGenerator.cs:147]: Verified with a generator test: `IEnvelope<Zebra>` and `IEnvelope<Animal>` (with `IEnvelope<out T>`) get the same supertype count, and the name tie-break emitted the broader arm first, which fails with CS8510. The name tie-break could also break a project that compiled before this PR, when arms simply followed declaration order.

Fixed in a965b3ed: the name tie-break is gone and the sort is stable, so equally specific types keep their discovery order. That is still deterministic, and anything that compiled before still compiles. Added `Should_keep_discovery_order_for_types_of_equal_specificity` as a regression test, and reworded the comment that claimed the rank alone guarantees no arm is subsumed.

Not doing the conversion-based topological ordering here. Variance-related message types declared broader-first failed before this PR too, so it is not a regression. Ordering them correctly needs implicit-conversion checks across all candidate pairs, on every generator run, over every `[EventType]` type in all referenced assemblies, and nobody has reported hitting this. It can be revisited if it comes up.

[the remark this answers is not in the document]
Comment (alexeyzimarev) [reply src/Core/gen/Eventuous.Subscriptions.Generators/ConsumeContextConverterGenerator.cs:147]: Verified with a generator test: `IEnvelope<Zebra>` and `IEnvelope<Animal>` (with `IEnvelope<out T>`) get the same supertype count, and the name tie-break emitted the broader arm first, which fails with CS8510. The name tie-break could also break a project that compiled before this PR, when arms simply followed declaration order.

Fixed in a965b3ed: the name tie-break is gone and the sort is stable, so equally specific types keep their discovery order. That is still deterministic, and anything that compiled before still compiles. Added `Should_keep_discovery_order_for_types_of_equal_specificity` as a regression test, and reworded the comment that claimed the rank alone guarantees no arm is subsumed.

Not doing the conversion-based topological ordering here. Variance-related message types declared broader-first failed before this PR too, so it is not a regression. Ordering them correctly needs implicit-conversion checks across all candidate pairs, on every generator run, over every `[EventType]` type in all referenced assemblies, and nobody has reported hitting this. It can be revisited if it comes up.
