### ISSUE TITLE
ConsumeContextConverterGenerator emits unreachable switch arms for inherited [EventType] records (CS8510) since 0.16.4

### ISSUE THREAD

**Issue by grimurd** [Eventuous/eventuous#589]
**Describe the bug**
Since 0.16.4 (PR #542), `ConsumeContextConverterGenerator` discovers all `[EventType]` types and emits one type-pattern switch arm per type in `MessageConsumeContext_Converters.g.cs`. The arms are emitted in discovery order with no inheritance-aware sorting, so when one `[EventType]` record inherits from another, the base-type arm can precede the derived-type arm. The derived arm is then subsumed and the build fails with `error CS8510: The pattern is unreachable`. The same code builds fine on 0.16.3.

In [`ConsumeContextConverterGenerator.cs`](https://github.com/Eventuous/eventuous/blob/0.16.4/src/Core/gen/Eventuous.Subscriptions.Generators/ConsumeContextConverterGenerator.cs):
- [`Generate`, L214](https://github.com/Eventuous/eventuous/blob/0.16.4/src/Core/gen/Eventuous.Subscriptions.Generators/ConsumeContextConverterGenerator.cs#L214) only applies `Distinct()` — no ordering — and [L241–L243](https://github.com/Eventuous/eventuous/blob/0.16.4/src/Core/gen/Eventuous.Subscriptions.Generators/ConsumeContextConverterGenerator.cs#L241-L243) emit the arms in that order.
- The order comes from [`DiscoverEventTypes`' namespace traversal, L257–L287](https://github.com/Eventuous/eventuous/blob/0.16.4/src/Core/gen/Eventuous.Subscriptions.Generators/ConsumeContextConverterGenerator.cs#L257-L287), which visits namespaces/types in declaration order — so a base type in namespace `Foo` is emitted before a derived type in `Foo.Bar`.

**To Reproduce**
1. Declare two event types where one inherits the other:
   ```csharp
   [EventType("V1.Base")]
   public record BaseEvent;

   [EventType("V1.Derived")]
   public sealed record DerivedEvent : BaseEvent;
   ```
2. Reference them from any project that uses Eventuous subscriptions (so the generator runs).
3. `dotnet build`
4. See `error CS8510: The pattern is unreachable. It has already been handled by a previous arm of the switch expression` in `MessageConsumeContext_Converters.g.cs`:
   ```csharp
   => context.Message switch {
       global::My.BaseEvent => new MessageConsumeContext<global::My.BaseEvent>(context),
       global::My.DerivedEvent => new MessageConsumeContext<global::My.DerivedEvent>(context), // CS8510
       _ => null
   };
   ```

**Expected behavior**
The generated switch compiles, and each message is matched to its most specific event type. Note the ordering is also a correctness issue: even where base-before-derived happens to compile, a derived event matches the base arm and gets wrapped as `MessageConsumeContext<BaseEvent>` instead of its concrete type.

A fix could sort arms most-derived-first before emitting — e.g. carry inheritance depth alongside the name from the `GetTypeSyntax` (L138) call sites and order by depth descending (then by name for deterministic incremental output) in `Generate` (L214):
```csharp
static int Depth(ITypeSymbol t) { var d = 0; for (var b = t.BaseType; b != null; b = b.BaseType) d++; return d; }
```
Any derived type is strictly deeper than its base, so no arm can subsume a later one — fixing both the CS8510 and the mismatched context type.

**Screenshots**
N/A — build output quoted above.

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 44)
 - .NET SDK: 10.0
 - Eventuous version: 0.16.4 (regression from 0.16.3)

**Additional context**
Introduced by the new `DiscoverEventTypes` step added in PR #542 (fix for #538), which scans the compilation and referenced assemblies for `[EventType]` types.
